export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAILED = "USER_LOADED_FAILED";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAILED = "AUTHENTICATED_FAILED";
export const LOGOUT = "LOGOUT";

export const PASSWORD_REST_FAIL = "PASSWORD_REST_FAIL";
export const PASSWORD_REST_SUCCESS = "PASSWORD_REST_SUCCESS";
export const PASSWORD_REST_CONFIRM_FAIL = "PASSWORD_REST_FAIL";
export const PASSWORD_REST_CONFIRM_SUCCESS = "PASSWORD_REST_SUCCESS";
